export const ADD_ITEM_TO_CART_REQUEST='ADD_ITEM_TO_CART_ID_REQUEST';
export const ADD_ITEM_TO_CART_SUCCESS='ADD_ITEM_TO_CART_ID_SUCCESS';
export const ADD_ITEM_TO_CART_FAILURE='FIND_CART_BY_ID_FAILURE';

export const GET_CART_REQUEST='GET_CARTS_REQUEST';
export const GET_CART_SUCCESS='GET_CARTS_SUCCESS';
export const GET_CART_FAILURE='FIND_CARTS_FAILURE';

export const REMOVE_CART_ITEM_REQUEST='GET_CARTS_REQUEST';
export const REMOVE_CART_ITEM_SUCCESS='GET_CARTS_SUCCESS';
export const REMOVE_CART_ITEM_FAILURE='FIND_CARTS_FAILURE';

export const UPDATE_CART_ITEM_REQUEST='GET_CARTS_REQUEST';
export const UPDATE_CART_ITEM_SUCCESS='GET_CARTS_SUCCESS';
export const UPDATE_CART_ITEM_FAILURE='FIND_CARTS_FAILURE';

